services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: finnet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build: ./server
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: finnet
      DB_USER: postgres
      DB_PASSWORD: postgres
      CORS_ALLOWED_ORIGIN: http://localhost:4200
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  client:
    build: ./client
    ports:
      - "4200:80"
    depends_on:
      - server

volumes:
  postgres-data:
